### ISSUE TITLE
Overhaul Movement System

### ISSUE THREAD

**Issue by floralvikings** [floralvikings/jenjin#163]
The inaccuracy of the current movement system is unacceptable.  The fact that the time stamp is essential to very part of the process (from finding location of change to calculating correct new position) makes it very difficult to improve accuracy using the current system.

Instead of doing that, I propose the following changes:
- [x] Send x and y coordinates along with other state change information (#162)
  - This will require more bandwidth, but will reduce computation time across the board.
- [x] Move actors based on `Actor.MOVE_SPEED` and the time since the previous step, instead of `Actor.STEP_LENGTH` (#172)
  - This will make is possible to have variable move speeds in the future, as well as fix the issues I've seen where actor movement would lose accuracy over time as discrepancies between updates accumulated.
  - This will also probably break a large number of tests, but might simplify a great deal of the test code.
- [x] Change the position correction system to use the time stamp and `Actor.MOVE_SPEED`.
  - This is going to cause a little bit of "overshoot" during the Actor's next step **but**...
  - If the Actor field that keeps track of step time is reset after the correction, the overshoot will be avoided.
- [x] Implement "broadcast staggering" (#164)
  - This will help compensate for the extra bandwidth being used to send player coordinates.
